name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - autodoc
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Adjust the version as needed

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme  # Ensure Sphinx dependencies are included

      # Build the documentation
      - name: Build Sphinx documentation
        run: |
          sphinx-build -b html docs/ docs/_build/html

      # Step 5: Upload the build artifact
      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/_build/html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write # Required for deployment
      id-token: write # Required for OIDC authentication

    steps:
      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
